# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='coord_mastec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='capturado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
