# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0004_auto_20180109_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mops',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.Contratista'),
        ),
        migrations.AlterField(
            model_name='mopslog',
            name='contratista_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mantenimiento.Contratista'),
        ),
    ]
