# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0005_auto_20180111_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='nota_mastec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
