# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0006_sitio_nota_mastec'),
    ]

    operations = [
        migrations.AddField(
            model_name='mops',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mops',
            name='nota_mastec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mopslog',
            name='eliminado_log',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mopslog',
            name='nota_mastec_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
