# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenimiento', '0007_auto_20180114_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='mops',
            name='cantidad_mop_ejecutada',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mopslog',
            name='cantidad_mop_ejecutada_log',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
